[package]
name = "flux-native"
version = "0.3.0"
edition = "2021"
description = "Flux – natívna verzia v Ruste (egui), bez Chromia"

[[bin]]
name = "flux-native"
path = "src/main.rs"

[build-dependencies]
embed-resource = "3"

[dependencies]
flux-core = { path = "../crates/flux-core" }
serde_json = "1"
dirs = "6"
eframe = { version = "0.36", default-features = false, features = ["glow", "wgpu", "default_fonts", "x11", "wayland"] }
egui_extras = { version = "0.36", features = ["syntect", "svg"] }
syntect = { version = "5.3", default-features = false, features = ["default-fancy"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "bmp", "webp", "gif"] }
alacritty_terminal = "0.26"
sha2 = "0.10"
rfd = "0.15"
notify = "8"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_ProcessStatus", "Win32_System_Threading", "Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }
windows = { version = "0.62", features = ["Win32_Media_MediaFoundation", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Variant"] }
