# Texty z 8. kola: kľúč (anglicky) → (sk, de, es, fr, it, pl)
_V8 = {
    "A GitHub window opened and Flux types this code into it for you:": ("Otvorilo sa okno GitHubu a Flux doň tento kód vpíše sám:", "Ein GitHub-Fenster hat sich geöffnet und Flux tippt diesen Code für dich ein:", "Se abrió una ventana de GitHub y Flux escribe este código por ti:", "Une fenêtre GitHub s'est ouverte et Flux y saisit ce code pour vous :", "Si è aperta una finestra di GitHub e Flux inserisce questo codice per te:", "Otworzyło się okno GitHuba i Flux sam wpisze ten kod:"),
    "Add to Claude Desktop": ("Pridať do Claude Desktop", "Zu Claude Desktop hinzufügen", "Añadir a Claude Desktop", "Ajouter à Claude Desktop", "Aggiungi a Claude Desktop", "Dodaj do Claude Desktop"),
    "Added to Claude Desktop. Restart Claude Desktop – then ask it about your Flux projects.": ("Pridané do Claude Desktop. Reštartuj Claude Desktop – potom sa ho opýtaj na svoje projekty vo Fluxe.", "Zu Claude Desktop hinzugefügt. Starte Claude Desktop neu – dann frag es nach deinen Flux-Projekten.", "Añadido a Claude Desktop. Reinicia Claude Desktop y pregúntale por tus proyectos de Flux.", "Ajouté à Claude Desktop. Redémarrez Claude Desktop, puis interrogez-le sur vos projets Flux.", "Aggiunto a Claude Desktop. Riavvia Claude Desktop e chiedigli dei tuoi progetti Flux.", "Dodano do Claude Desktop. Uruchom go ponownie i zapytaj o swoje projekty we Fluxie."),
    "Anyone with the key can change your projects – do not share it.": ("Kto má kľúč, môže meniť tvoje projekty – nikomu ho nedávaj.", "Wer den Schlüssel hat, kann deine Projekte ändern – gib ihn nicht weiter.", "Quien tenga la clave puede cambiar tus proyectos: no la compartas.", "Quiconque a la clé peut modifier vos projets – ne la partagez pas.", "Chi ha la chiave può modificare i tuoi progetti – non condividerla.", "Każdy z tym kluczem może zmieniać twoje projekty – nie udostępniaj go."),
    "ChatGPT and claude.ai in the browser can only connect to servers on the internet, not to apps on your computer – use Claude Desktop, Claude Code or Cursor.": ("ChatGPT a claude.ai v prehliadači sa vedia pripojiť len na servery na internete, nie na aplikácie v tvojom počítači – použi Claude Desktop, Claude Code alebo Cursor.", "ChatGPT und claude.ai im Browser können sich nur mit Servern im Internet verbinden, nicht mit Apps auf deinem Computer – nutze Claude Desktop, Claude Code oder Cursor.", "ChatGPT y claude.ai en el navegador solo se conectan a servidores en internet, no a apps de tu equipo: usa Claude Desktop, Claude Code o Cursor.", "ChatGPT et claude.ai dans le navigateur ne peuvent se connecter qu'à des serveurs sur internet, pas aux applis de votre ordinateur – utilisez Claude Desktop, Claude Code ou Cursor.", "ChatGPT e claude.ai nel browser si collegano solo a server su internet, non alle app del tuo computer – usa Claude Desktop, Claude Code o Cursor.", "ChatGPT i claude.ai w przeglądarce łączą się tylko z serwerami w internecie, nie z aplikacjami na komputerze – użyj Claude Desktop, Claude Code lub Cursor."),
    "Connect an app": ("Pripojiť aplikáciu", "App verbinden", "Conectar una app", "Connecter une appli", "Collega un'app", "Połącz aplikację"),
    "Copied – paste it into a terminal.": ("Skopírované – vlož to do terminálu.", "Kopiert – füge es in ein Terminal ein.", "Copiado: pégalo en una terminal.", "Copié – collez-le dans un terminal.", "Copiato – incollalo in un terminale.", "Skopiowano – wklej to do terminala."),
    "Copied – paste it into mcp.json of Cursor or VS Code.": ("Skopírované – vlož to do mcp.json v Cursore alebo VS Code.", "Kopiert – füge es in die mcp.json von Cursor oder VS Code ein.", "Copiado: pégalo en mcp.json de Cursor o VS Code.", "Copié – collez-le dans mcp.json de Cursor ou VS Code.", "Copiato – incollalo in mcp.json di Cursor o VS Code.", "Skopiowano – wklej to do mcp.json w Cursorze lub VS Code."),
    "If the code is not filled in, click the first box and press Ctrl+V – it is already copied.": ("Ak sa kód nevyplní, klikni do prvého políčka a stlač Ctrl+V – je už skopírovaný.", "Wenn der Code nicht erscheint, klicke ins erste Feld und drücke Strg+V – er ist schon kopiert.", "Si el código no aparece, haz clic en la primera casilla y pulsa Ctrl+V: ya está copiado.", "Si le code n'apparaît pas, cliquez dans la première case et appuyez sur Ctrl+V – il est déjà copié.", "Se il codice non compare, clicca nella prima casella e premi Ctrl+V – è già copiato.", "Jeśli kod się nie wpisze, kliknij pierwsze pole i naciśnij Ctrl+V – jest już skopiowany."),
    "Let AI apps use Flux": ("Povoliť AI aplikáciám používať Flux", "AI-Apps Flux nutzen lassen", "Permitir que las apps de IA usen Flux", "Laisser les applis d'IA utiliser Flux", "Consenti alle app di IA di usare Flux", "Pozwól aplikacjom AI używać Fluxa"),
    "Link": ("Odkaz", "Link", "Enlace", "Lien", "Link", "Link"),
    "Log in to GitHub if it asks (also with Google).": ("Prihlás sa na GitHub, ak si to vypýta (aj cez Google).", "Melde dich bei GitHub an, falls gefragt (auch mit Google).", "Inicia sesión en GitHub si te lo pide (también con Google).", "Connectez-vous à GitHub si demandé (aussi avec Google).", "Accedi a GitHub se richiesto (anche con Google).", "Zaloguj się do GitHuba, jeśli poprosi (także przez Google)."),
    "New key": ("Nový kľúč", "Neuer Schlüssel", "Nueva clave", "Nouvelle clé", "Nuova chiave", "Nowy klucz"),
    "New key made. Connect your AI apps again.": ("Nový kľúč je hotový. Pripoj AI aplikácie znova.", "Neuer Schlüssel erstellt. Verbinde deine AI-Apps erneut.", "Nueva clave creada. Vuelve a conectar tus apps de IA.", "Nouvelle clé créée. Reconnectez vos applis d'IA.", "Nuova chiave creata. Ricollega le tue app di IA.", "Nowy klucz utworzony. Połącz aplikacje AI ponownie."),
    "One click for Claude Desktop (restart it afterwards); the others get a ready command to paste.": ("Jedným klikom pre Claude Desktop (potom ho reštartuj); pre ostatné sa skopíruje hotový príkaz na vloženie.", "Ein Klick für Claude Desktop (danach neu starten); für die anderen wird ein fertiger Befehl kopiert.", "Un clic para Claude Desktop (reinícialo después); para las demás se copia un comando listo para pegar.", "Un clic pour Claude Desktop (redémarrez-le ensuite) ; pour les autres, une commande prête à coller est copiée.", "Un clic per Claude Desktop (poi riavvialo); per le altre viene copiato un comando pronto da incollare.", "Jedno kliknięcie dla Claude Desktop (potem uruchom go ponownie); dla innych kopiowane jest gotowe polecenie."),
    "Running – AI apps can connect now.": ("Beží – AI aplikácie sa môžu pripojiť.", "Läuft – AI-Apps können sich jetzt verbinden.", "En marcha: las apps de IA ya pueden conectarse.", "Actif – les applis d'IA peuvent se connecter.", "Attivo – le app di IA possono collegarsi.", "Działa – aplikacje AI mogą się połączyć."),
    "Secret key": ("Tajný kľúč", "Geheimer Schlüssel", "Clave secreta", "Clé secrète", "Chiave segreta", "Tajny klucz"),
    "Use Flux from other AI apps": ("Flux v iných AI aplikáciách", "Flux in anderen AI-Apps", "Usar Flux desde otras apps de IA", "Utiliser Flux depuis d'autres applis d'IA", "Usa Flux da altre app di IA", "Flux w innych aplikacjach AI"),
    "Use my browser instead": ("Radšej v mojom prehliadači", "Lieber meinen Browser nutzen", "Usar mi navegador", "Utiliser mon navigateur", "Usa il mio browser", "Użyj mojej przeglądarki"),
    "Claude, Cursor and other apps that support MCP can see and change your Flux projects – files, description and to-do list. It works only on this computer and needs a secret key.": ("", "", "", "", "", ""),
    "Claude Desktop settings could not be read: {msg}": ("Nastavenia Claude Desktop sa nepodarilo načítať: {msg}", "Die Einstellungen von Claude Desktop konnten nicht gelesen werden: {msg}", "No se pudo leer la configuración de Claude Desktop: {msg}", "Impossible de lire les réglages de Claude Desktop : {msg}", "Impossibile leggere le impostazioni di Claude Desktop: {msg}", "Nie udało się odczytać ustawień Claude Desktop: {msg}"),
    "Claude Desktop, Claude Code, Cursor and other apps that support MCP can see and change your Flux projects – files, description and to-do list. It works only on this computer and needs a secret key.": ("Claude Desktop, Claude Code, Cursor a ďalšie aplikácie s podporou MCP vidia a menia tvoje projekty vo Fluxe – súbory, popis aj úlohy. Funguje to len v tomto počítači a treba tajný kľúč.", "Claude Desktop, Claude Code, Cursor und andere Apps mit MCP können deine Flux-Projekte sehen und ändern – Dateien, Beschreibung und To-dos. Das funktioniert nur auf diesem Computer und braucht einen geheimen Schlüssel.", "Claude Desktop, Claude Code, Cursor y otras apps con MCP pueden ver y cambiar tus proyectos de Flux: archivos, descripción y tareas. Solo funciona en este equipo y necesita una clave secreta.", "Claude Desktop, Claude Code, Cursor et d'autres applis compatibles MCP peuvent voir et modifier vos projets Flux – fichiers, description et tâches. Cela ne fonctionne que sur cet ordinateur et nécessite une clé secrète.", "Claude Desktop, Claude Code, Cursor e altre app con MCP possono vedere e modificare i tuoi progetti Flux – file, descrizione e attività. Funziona solo su questo computer e richiede una chiave segreta.", "Claude Desktop, Claude Code, Cursor i inne aplikacje z MCP mogą widzieć i zmieniać twoje projekty we Fluxie – pliki, opis i zadania. Działa tylko na tym komputerze i wymaga tajnego klucza."),
}
_V8 = {k: v for k, v in _V8.items() if v[0]}
V8 = {code: {k: v[i] for k, v in _V8.items()} for i, code in enumerate(['sk', 'de', 'es', 'fr', 'it', 'pl'])}
